### ISSUE TITLE
Not able to install the dependency

### ISSUE THREAD

**Issue by HrithikMittal** [akshitgrover/box-exec#1]
![image](https://user-images.githubusercontent.com/42075023/52423167-8bbd5d80-2b1d-11e9-856d-5db6ed367535.png)

I also try with 

`npm install -g box-exec`

and also try by saving but it is not working

**Comment by akshitgrover** [comment]
It is an issue in version 2.0.1, Try installing version 2.0.0.
2.0.1 is not stable there is a bug which will be fixed in coming release probably by the end of this week.

**Comment by HrithikMittal** [comment]
Ya it is working @version 2.0.0 
thank you for your support.
